schema: "classroom50/repo-config/v1"
classroom: "f215-digital-design"
assignment: "dd-2026-verilog-labs"
owner:
  username: "Parth20250654"
  id: 318479892
  accepted_at: "2026-08-28T05:10:16Z"
source:
  owner: "f2152026"
  owner_id: 316136693
  repo: "verilog-labs"
  branch: "main"
